controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    manual_controller:
      type: forward_command_controller/ForwardCommandController

manual_controller:
  ros__parameters:
    joints:
      - base_yaw
      - shoulder_extension
      - elbow_extension
      - wrist_roll
      - wrist_twist
      - claw

    interface_name: velocity
