/science/controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    science_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    beaker_position_controller:
      type: position_controllers/JointGroupPositionController


/science/science_velocity_controller:
  ros__parameters:
    joints:
      - science_lift_joint
      - auger_spin_joint


/science/beaker_position_controller:
  ros__parameters:
    joints:
      - beaker_tray_joint
